// import type { Job } from "@/types/job";

// // Track B: replace with real API data from GET /jobs
// export const mockJobs: Job[] = [
//   {
//     id: "job-1",
//     title: "React Frontend Developer for SaaS Dashboard",
//     description:
//       "We need an experienced React developer to build out a data-heavy admin dashboard with charts, tables, and real-time updates. Must be comfortable with TypeScript and REST APIs.",
//     category: "Web Development",
//     skills: ["React", "TypeScript", "Tailwind CSS", "REST APIs"],
//     budgetType: "FIXED",
//     budgetMin: 1500,
//     budgetMax: 3000,
//     experienceLevel: "Intermediate",
//     status: "OPEN",
//     clientName: "NexTek Labs",
//     clientId: "client-1",
//     applicantCount: 14,
//     postedAt: "2026-08-18",
//   },
//   {
//     id: "job-2",
//     title: "Mobile App UI Design (Fintech)",
//     description:
//       "Looking for a designer to create a modern, trustworthy UI for a personal finance tracking app. Deliverables include Figma files and a component library.",
//     category: "Design",
//     skills: ["Figma", "UI Design", "Mobile Design", "Design Systems"],
//     budgetType: "FIXED",
//     budgetMin: 800,
//     budgetMax: 1500,
//     experienceLevel: "Expert",
//     status: "OPEN",
//     clientName: "Finlytic",
//     clientId: "client-2",
//     applicantCount: 22,
//     postedAt: "2026-08-20",
//   },
//   {
//     id: "job-3",
//     title: "Node.js Backend for Marketplace Platform",
//     description:
//       "Build REST APIs for a two-sided marketplace: auth, listings, payments webhook handling. Prisma + PostgreSQL experience required.",
//     category: "Web Development",
//     skills: ["Node.js", "Express", "PostgreSQL", "Prisma"],
//     budgetType: "HOURLY",
//     budgetMin: 20,
//     budgetMax: 35,
//     experienceLevel: "Expert",
//     status: "OPEN",
//     clientName: "Marketloop Inc.",
//     clientId: "client-3",
//     applicantCount: 9,
//     postedAt: "2026-08-15",
//   },
//   {
//     id: "job-4",
//     title: "Content Writer for SaaS Blog",
//     description:
//       "Write 4 long-form blog posts per month on B2B SaaS topics. Must understand technical products and write in a clear, engaging voice.",
//     category: "Writing",
//     skills: ["Content Writing", "SEO", "B2B Marketing"],
//     budgetType: "HOURLY",
//     budgetMin: 15,
//     budgetMax: 25,
//     experienceLevel: "Intermediate",
//     status: "OPEN",
//     clientName: "CloudBase",
//     clientId: "client-4",
//     applicantCount: 31,
//     postedAt: "2026-08-21",
//   },
//   {
//     id: "job-5",
//     title: "iOS App Developer — Swift",
//     description:
//       "Native iOS app for a fitness tracking startup. Looking for someone who can own the app from architecture to App Store submission.",
//     category: "Mobile Development",
//     skills: ["Swift", "SwiftUI", "iOS", "HealthKit"],
//     budgetType: "FIXED",
//     budgetMin: 4000,
//     budgetMax: 7000,
//     experienceLevel: "Expert",
//     status: "OPEN",
//     clientName: "FitPulse",
//     clientId: "client-5",
//     applicantCount: 6,
//     postedAt: "2026-08-19",
//   },
//   {
//     id: "job-6",
//     title: "Social Media Marketing Manager",
//     description:
//       "Manage Instagram and TikTok presence for a D2C skincare brand. Content calendar, community engagement, and monthly reporting.",
//     category: "Marketing",
//     skills: ["Social Media", "Content Strategy", "Analytics"],
//     budgetType: "HOURLY",
//     budgetMin: 18,
//     budgetMax: 28,
//     experienceLevel: "Entry",
//     status: "OPEN",
//     clientName: "Glowvana",
//     clientId: "client-6",
//     applicantCount: 40,
//     postedAt: "2026-08-22",
//   },
//   {
//     id: "job-7",
//     title: "Data Analyst — Customer Churn Modeling",
//     description:
//       "Analyze subscription data to identify churn drivers and build a predictive model. Python + SQL required.",
//     category: "Data Science",
//     skills: ["Python", "SQL", "Pandas", "Machine Learning"],
//     budgetType: "FIXED",
//     budgetMin: 2000,
//     budgetMax: 3500,
//     experienceLevel: "Intermediate",
//     status: "OPEN",
//     clientName: "RetainIQ",
//     clientId: "client-7",
//     applicantCount: 11,
//     postedAt: "2026-08-17",
//   },
//   {
//     id: "job-8",
//     title: "Landing Page Design + Build",
//     description:
//       "Design and build a single high-converting landing page for a product launch. Figma design followed by a responsive Next.js build.",
//     category: "Web Development",
//     skills: ["Next.js", "Tailwind CSS", "Figma", "Framer Motion"],
//     budgetType: "FIXED",
//     budgetMin: 600,
//     budgetMax: 1200,
//     experienceLevel: "Intermediate",
//     status: "OPEN",
//     clientName: "Launchpad Studio",
//     clientId: "client-8",
//     applicantCount: 27,
//     postedAt: "2026-08-16",
//   },
//   {
//     id: "job-9",
//     title: "Flutter Developer for Cross-Platform App",
//     description:
//       "Extend an existing Flutter app with new features: push notifications, in-app purchases, and offline sync.",
//     category: "Mobile Development",
//     skills: ["Flutter", "Dart", "Firebase"],
//     budgetType: "HOURLY",
//     budgetMin: 22,
//     budgetMax: 32,
//     experienceLevel: "Intermediate",
//     status: "OPEN",
//     clientName: "Wanderlist",
//     clientId: "client-9",
//     applicantCount: 8,
//     postedAt: "2026-08-14",
//   },
//   {
//     id: "job-10",
//     title: "Technical Documentation Writer",
//     description:
//       "Rewrite and expand our developer documentation for a public API. Experience with docs-as-code workflows preferred.",
//     category: "Writing",
//     skills: ["Technical Writing", "API Documentation", "Markdown"],
//     budgetType: "FIXED",
//     budgetMin: 1000,
//     budgetMax: 1800,
//     experienceLevel: "Intermediate",
//     status: "OPEN",
//     clientName: "DevBridge",
//     clientId: "client-10",
//     applicantCount: 5,
//     postedAt: "2026-08-13",
//   },
//   {
//     id: "job-11",
//     title: "Junior Frontend Developer (Vue)",
//     description:
//       "Great opportunity for someone early in their career to work on a real production Vue 3 app under senior mentorship.",
//     category: "Web Development",
//     skills: ["Vue.js", "JavaScript", "CSS"],
//     budgetType: "HOURLY",
//     budgetMin: 10,
//     budgetMax: 18,
//     experienceLevel: "Entry",
//     status: "OPEN",
//     clientName: "Northstar Apps",
//     clientId: "client-11",
//     applicantCount: 52,
//     postedAt: "2026-08-23",
//   },
//   {
//     id: "job-12",
//     title: "Brand Identity & Logo Design",
//     description:
//       "New startup needs a full brand identity: logo, color palette, typography guide, and basic brand book.",
//     category: "Design",
//     skills: ["Branding", "Logo Design", "Illustrator"],
//     budgetType: "FIXED",
//     budgetMin: 500,
//     budgetMax: 900,
//     experienceLevel: "Intermediate",
//     status: "CLOSED",
//     clientName: "Orbit Coffee Co.",
//     clientId: "client-12",
//     applicantCount: 63,
//     postedAt: "2026-08-05",
//   },
// ];
